{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ele",
    "module": "lancet-base",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lancet-base-1.0.7.jar",
          "url": "lancet-base-1.0.7.jar",
          "size": 6085,
          "sha512": "7b8e2c755464ce901cc35d473487f6a9aecaf1b491b114c39d813958da598c477ae02dd7710efa49ef0e932a1e5dea2e22bdeeb0ebc73b4dd9d666c46f854ad2",
          "sha256": "2b6d24cc4ace3513d1ec08a7ba6ad32cf08fc8e40fe56b2ac01ef14565bfd17b",
          "sha1": "de08a431c75b5c169ed437a3bc1c3830045ab921",
          "md5": "81be9f2be7b5108975260e7d01408bd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lancet-base-1.0.7.jar",
          "url": "lancet-base-1.0.7.jar",
          "size": 6085,
          "sha512": "7b8e2c755464ce901cc35d473487f6a9aecaf1b491b114c39d813958da598c477ae02dd7710efa49ef0e932a1e5dea2e22bdeeb0ebc73b4dd9d666c46f854ad2",
          "sha256": "2b6d24cc4ace3513d1ec08a7ba6ad32cf08fc8e40fe56b2ac01ef14565bfd17b",
          "sha1": "de08a431c75b5c169ed437a3bc1c3830045ab921",
          "md5": "81be9f2be7b5108975260e7d01408bd6"
        }
      ]
    }
  ]
}
