{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ele",
    "module": "lancet-weaver",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lancet-weaver-1.0.7.jar",
          "url": "lancet-weaver-1.0.7.jar",
          "size": 118404,
          "sha512": "b30b9b56e045b107e480e239888ef142b9ad90f27c45d91d938fc2bc4416d95cf5322945f69bd34377d9fbb16483150671c3f0d6611165a392f4c4206ae55d15",
          "sha256": "66969beb3370aa3ec24b63f5aa1aedd6090b20a45d70886a17496f7609bbd16e",
          "sha1": "d0193920afec4fa944edd3f5904aa32a7238b808",
          "md5": "c8aa8abef54a157964375ee5de72754a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "me.ele",
          "module": "lancet-base",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "lancet-weaver-1.0.7.jar",
          "url": "lancet-weaver-1.0.7.jar",
          "size": 118404,
          "sha512": "b30b9b56e045b107e480e239888ef142b9ad90f27c45d91d938fc2bc4416d95cf5322945f69bd34377d9fbb16483150671c3f0d6611165a392f4c4206ae55d15",
          "sha256": "66969beb3370aa3ec24b63f5aa1aedd6090b20a45d70886a17496f7609bbd16e",
          "sha1": "d0193920afec4fa944edd3f5904aa32a7238b808",
          "md5": "c8aa8abef54a157964375ee5de72754a"
        }
      ]
    }
  ]
}
