{
  "formatVersion": "1.1",
  "component": {
    "group": "me.ele",
    "module": "lancet-plugin",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lancet-plugin-1.0.7.jar",
          "url": "lancet-plugin-1.0.7.jar",
          "size": 44284,
          "sha512": "12025ae9e2ecf47d7314bea7b8f17d7d813c1df3368ff4d0767d76c1c64ed7396be82c9af7a6055bd1afad6563b7e166d63c5cfb1e0d91558a5ae042491ed0ee",
          "sha256": "7d79eda6d2606989c6dd974230f2f7b859a3f944917bfde8d79bc4a41d272035",
          "sha1": "d2ab256deb0300198f96e4521351f0f69f397fdd",
          "md5": "6539f40605daa2c30665a90fb53f1e8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "me.ele",
          "module": "lancet-weaver",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "me.ele",
          "module": "lancet-base",
          "version": {
            "requires": "1.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "lancet-plugin-1.0.7.jar",
          "url": "lancet-plugin-1.0.7.jar",
          "size": 44284,
          "sha512": "12025ae9e2ecf47d7314bea7b8f17d7d813c1df3368ff4d0767d76c1c64ed7396be82c9af7a6055bd1afad6563b7e166d63c5cfb1e0d91558a5ae042491ed0ee",
          "sha256": "7d79eda6d2606989c6dd974230f2f7b859a3f944917bfde8d79bc4a41d272035",
          "sha1": "d2ab256deb0300198f96e4521351f0f69f397fdd",
          "md5": "6539f40605daa2c30665a90fb53f1e8e"
        }
      ]
    }
  ]
}
